### ISSUE TITLE
The sheet won't render

### ISSUE THREAD

**Issue by dczwardCZAR** [Handyfon/Darksheet#38]
I am getting an error when I try to open a Darksheet5e character sheet.

My environment:
FVTT v10.291
DnD5e v2.1.5
Darksheet5e v10.1.1

The error occurs with only Darksheet5e enabled (using "Find the Culprit!")

here's the console error...

foundry.js:5099 Foundry VTT | Rendering DarkSheet
foundry.js:747 TypeError: An error occurred while rendering DarkSheet 102. Cannot set property hasTarget of #<Item5e> which has only a getter
[Detected 4 packages: darksheet, system:dnd5e, item-piles, lib-wrapper]
    at character.js:49:22
    at Array.reduce (<anonymous>)
    at DarkSheet._prepareItems (character.js:27:54)
    at DarkSheet.getData (base-sheet.mjs:163:10)
    at DarkSheet.getData (character-sheet.mjs:23:33)
    at DarkSheet.getData (character.js:5:29)
    at DarkSheet.getData (darksheet.js:851:28)
    at DarkSheet._render (foundry.js:5108:29)
    at DarkSheet._render (foundry.js:5822:17)
    at DarkSheet.render (foundry.js:5067:10)
    at DarkSheet.render (foundry.js:6394:18)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁ActorSheet.prototype.render#item-piles (libwrapper.js:35:12)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at 🎁ActorSheet.prototype.render#0 (libWrapper-wrapper.js:189:20)
    at Token5e._onClickLeft2 (foundry.js:47378:16)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁Token.prototype._onClickLeft2#item-piles (libwrapper.js:13:12)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at 🎁Token.prototype._onClickLeft2#0 (libWrapper-wrapper.js:189:20)
    at MouseInteractionManager.callback (foundry.js:27813:45)
    at MouseInteractionManager._handleClickLeft2 (foundry.js:28027:17)
    at MouseInteractionManager._handleMouseDown (foundry.js:27989:66)
    at a.emit (index.js:181:35)
    at r.dispatchEvent (interaction.min.mjs:8:12235)
    at r.processPointerDown (interaction.min.mjs:8:14214)
    at t.recursiveFindHit (interaction.min.mjs:8:4098)
    at t.recursiveFindHit (interaction.min.mjs:8:3882)
    at t.recursiveFindHit (interaction.min.mjs:8:3882)
    at t.recursiveFindHit (interaction.min.mjs:8:3882)
    at t.recursiveFindHit (interaction.min.mjs:8:3882)
    at t.recursiveFindHit (interaction.min.mjs:8:3882)
    at t.findHit (interaction.min.mjs:8:4157)
    at r.processInteractive (interaction.min.mjs:8:12841)
    at r.onPointerDown (interaction.min.mjs:8:13543)
onError @ foundry.js:747
🎁call_wrapped @ libWrapper-wrapper.js:507
🎁Hooks.onError#lib-wrapper @ listeners.js:138
🎁Hooks.onError#0 @ libWrapper-wrapper.js:187
(anonymous) @ foundry.js:5069
Promise.catch (async)
render @ foundry.js:5067
render @ foundry.js:6394
🎁call_wrapped @ libWrapper-wrapper.js:507
🎁ActorSheet.prototype.render#item-piles @ libwrapper.js:35
🎁call_wrapper @ libWrapper-wrapper.js:616
🎁ActorSheet.prototype.render#0 @ libWrapper-wrapper.js:189
_onClickLeft2 @ foundry.js:47378
🎁call_wrapped @ libWrapper-wrapper.js:507
🎁Token.prototype._onClickLeft2#item-piles @ libwrapper.js:13
🎁call_wrapper @ libWrapper-wrapper.js:616
🎁Token.prototype._onClickLeft2#0 @ libWrapper-wrapper.js:189
callback @ foundry.js:27813
_handleClickLeft2 @ foundry.js:28027
_handleMouseDown @ foundry.js:27989
a.emit @ index.js:181
r.dispatchEvent @ interaction.min.mjs:8
r.processPointerDown @ interaction.min.mjs:8
t.recursiveFindHit @ interaction.min.mjs:8
t.recursiveFindHit @ interaction.min.mjs:8
t.recursiveFindHit @ interaction.min.mjs:8
t.recursiveFindHit @ interaction.min.mjs:8
t.recursiveFindHit @ interaction.min.mjs:8
t.recursiveFindHit @ interaction.min.mjs:8
t.findHit @ interaction.min.mjs:8
r.processInteractive @ interaction.min.mjs:8
r.onPointerDown @ interaction.min.mjs:8

**Comment by Handyfon** [comment]
fixed with update
